### ISSUE TITLE
Error: Failed to install 'threadr' from GitHub:   'local_makevars' is not an exported object from 'namespace:withr'

### ISSUE THREAD

**Issue by nish-aj** [skgrange/threadr#7]
Hello,
I keep getting this error while trying to install the thread package using the below code

`install.packages("remotes")
remotes::install_github("skgrange/threadr")`
**Error: Failed to install 'threadr' from GitHub:   'local_makevars' is not an exported object from 'namespace:withr'**

Could someone please help?

**Comment by skgrange** [comment]
Hello. That sounds like an issue with locked directories and/or library files. It is a bit odd because I do not recognise the `withr` message. 

I would recommend restarting your R session and making sure your restarted environment is completely clear and empty. After that, you can try the `remotes::install_github("skgrange/threadr")` command again. I hope that helps!
